INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Francisca Macarena', 'Bustos Péndola', '+56981879250', 'franciscambp@outlook.com', '1996-01-15', 'estudiante', 'universidad del bío-bío', 'Fonasa', 'soltera', 'Mamá, papá, una hermana', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Rodrigo Ignacio', 'Valenzuela Ortiz', '+56945369821', 'francisca.bustos.pendola@gmail.com', '1990-02-27', 'estudiante', 'universidad del desarrollo', 'Isapre', 'soltero', 'Mamá y hermano', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Camilo', 'Vergara Fuenzalida', '+56925630014', 'francisca.bustos1401@alumnos.ubiobio.cl', '1998-07-29', 'estudiante', 'universidad de concepción', 'Fonasa', 'soltero', 'Mamá, papá, una hermana', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Jorge Alonso', 'Romero Vidal', '+56977445830', 'francisca.bustos.pendola@gmail.com', '1980-12-20', 'Ingeniero Civil', 'Constructora', 'Isapre', 'Casado', 'Esposa, dos hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Javiera Ignacia', 'Riquelme Pereira', '+56920305674', 'franciscambp@outlook.com', '1987-03-15', 'estudiante', 'universidad de concepción', 'Fonasa', 'Casada', 'Marido, sin hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Vanessa', 'Venegas Jorquera', '+56911224785', 'francisca.bustos1401@alumnos.ubiobio.cl', '1976-11-29', 'Dueña de casa', '-', 'Fonasa', 'Casada', 'Marido, tres hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Renata', 'Marisio Hidalgo', '+56914009988', 'franciscambp@outlook.com', '1985-05-14', 'Psicóloga', 'independiente', 'Fonasa', 'soltera', 'Mamá, papá', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Ramiro Camilo', 'Giacomozzi Teuber', '+56963007452', 'francisca.bustos1401@alumnos.ubiobio.cl', '1999-02-01', 'estudiante', 'colegio concepción', 'Isapre', 'soltero', 'Mamá, papá, tres hermanos, una hermana', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Ignacio', 'Hermosilla García', '+56900524789', 'francisca.bustos.pendola@gmail.com', '1970-10-25', 'Contador', 'Banco de chile', 'Fonasa', 'Divorciado', 'una hija', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Tomás Javier', 'Valencia Verdugo', '+56914209852', 'francisca.bustos.pendola@gmail.com', '1979-11-01', 'Abogado', 'Valencia & asociados', 'Isapre', 'Casado', 'Esposa', 'Inactivo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Agustina Fernanda', 'Mackenna Toledo', '+56932007458', 'francisca.bustos.pendola@gmail.com', '1980-04-20', 'Chef', 'Restaurant delicias del sur', 'Fonasa', 'Divorciada', 'dos hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Valentina Cataline', 'Arriagada Avello', '+56925003698', 'franciscambp@outlook.com', '2010-06-30', 'estudiante', 'Colegio Padre Hurtado', 'Isapre', 'soltera', 'Mamá, papá, un hermano, dos hermanas', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Catalina Paz', 'Riquelme Soto', '+56925639874', 'franciscambp@outlook.com', '2001-06-12', 'estudiante', 'universidad de concepción', 'Fonasa', 'soltera', 'Mamá, papá (hija única)', 'Inactivo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Laura Angélica', 'Brevis Maldonado', '+56985001147', 'francisca.bustos1401@alumnos.ubiobio.cl', '1994-02-01', 'Nutricionista', 'Centro médico manantial', 'Fonasa', 'Casada', 'Marido, una hija', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Camila Andrea', 'Pereira Ortiz', '+56914520098', 'francisca.bustos1401@alumnos.ubiobio.cl', '1990-07-13', 'Fonoaudiologa', 'Clínica Chillán', 'Isapre', 'Casada', 'Marido, un hijo', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Beatriz', 'Jorquera Jaque', '+56911558632', 'francisca.bustos1401@alumnos.ubiobio.cl', '1965-12-01', 'Dueña de casa', '-', 'Fonasa', 'Divorciada', 'Dos hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Francisca Ignacia', 'Rebolledo Toledo', '+56914235800', 'franciscambp@outlook.com', '1979-11-14', 'Kinesiologa', 'Centro médico manantial', 'Isapre', 'Soltera', 'Pololo, madre, padre, tres hermanas', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Ramiro Hernán', 'Concha Hermosilla', '+56914205638', 'franciscambp@outlook.com', '1982-08-15', 'Abogado', 'Firma', 'Isapre', 'Casado', 'Esposa, dos hijos', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Francisca Fernanda', 'Bravo Riquelme', '+56914520698', 'francisca.bustos.pendola@gmail.com', '1975-03-26', 'Ingeniera en Construcción', 'Constructora Fuenzalida', 'Fonasa', 'Casada', 'Marido, una hija', 'Activo', NULL, NULL);
INSERT INTO paciente (nombre, apellido, telefono, email, fecha_nacimiento, ocupacion, institucion, afiliacion_salud, estado_civil, familia_nuclear, estado, id_ficha, id_anamnesis) VALUES ('Francisca Angélica', 'Romero Teuber', '+56914250396', 'francisca.bustos.pendola@gmail.com', '1980-06-17', 'Doctora', 'Clínica Amapola', 'Isapre', 'Casada', 'Marido, sin hijos', 'Activo', NULL, NULL);

INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, NOW(), '08:00', 6, 15, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, 1, NOW(), '12:00', 1, 5, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, NOW(), '16:00', 2, 15, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, NOW(), '19:10', 1, 20, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, NOW(), '09:20', 3, 15, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, -1, NOW(), '10:30', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, 1, NOW(), '08:50', 2, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, NOW(), '17:30', 4, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, NOW(), '18:15', 2, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, NOW(), '15:10', 3, 18, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, NOW(), '20:00', 6, 15, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (0, 0, '2021-06-14', '16:00', 4, 20, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, '2021-05-12', '10:30', 2, 11, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, -1, '2021-05-11', '11:20', 2, 16, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2021-06-14', '15:30', 5, 14, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 0, '2021-05-15', '12:00', 1, 15, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (0, 0, '2021-06-14', '17:30', 4, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, 1, '2021-06-14', '13:00', 3, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (0, 0, '2021-06-14', '17:30', 2, 16, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2021-05-12', '18:40', 1, 4, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2020-06-24', '11:20', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, -1, '2020-10-15', '12:00', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, 1, '2020-12-28', '17:30', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2019-11-01', '12:00', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, -1, '2019-09-15', '10:30', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2019-06-14', '18:10', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (1, 1, '2019-08-18', '19:00', 6, 1, NULL);
INSERT INTO hora_atencion(asistencia, confirma_asistencia, fecha_atencion, hora_atencion, nro_consulta, id_paciente, id_pago) VALUES (-1, -1, '2019-04-29', '10:30', 6, 1, NULL);

INSERT INTO ficha_tratamiento(motivo_consulta_profesional, fecha_diagnostico, resultado_diagnostico, sugerencia_tratamiento, objetivos_terapia, estado) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel pretium odio, non fermentum augue. Fusce luctus et ligula ut consequat. Morbi magna purus, aliquet vestibulum auctor at, aliquet nec risus. Proin quis viverra ex. Maecenas lacus neque, euismod nec volutpat at, condimentum vitae lacus. Curabitur vehicula mi sed sem pulvinar aliquet sed sed ipsum. Fusce scelerisque egestas porttitor.', NOW(), 'Sed luctus lobortis augue, non pharetra lectus lobortis vel. Mauris id vulputate arcu. Duis imperdiet orci vel tortor lacinia, a congue ipsum pellentesque. ', 'Nullam non vestibulum tellus. Proin semper pellentesque rhoncus. Vestibulum auctor mi turpis, sed sodales leo dictum a. Proin bibendum nunc tincidunt, auctor magna sed, lacinia neque. Mauris faucibus, libero at rutrum rhoncus, ipsum nunc rhoncus nunc, eget sagittis ex augue sed magna.', 'Integer nec purus dapibus, laoreet neque ut, fermentum urna. Pellentesque eu gravida lacus. Ut laoreet nisi nunc. Mauris pharetra malesuada ex, ut sollicitudin felis bibendum a. ', 'Activo');
INSERT INTO ficha_tratamiento(motivo_consulta_profesional, fecha_diagnostico, resultado_diagnostico, sugerencia_tratamiento, objetivos_terapia, estado) VALUES ('Cras elementum lorem quis feugiat commodo. Phasellus non ligula et velit aliquet pharetra eget in enim. Nulla eget consequat arcu. Proin volutpat at sem vel hendrerit. Aliquam porttitor velit sit amet erat tincidunt, id tincidunt lorem lacinia. ', NOW(), 'Suspendisse sit amet sem et ipsum cursus tempor. Nunc quis nulla nisi. Suspendisse nunc mauris, fermentum nec turpis eu, scelerisque imperdiet eros. Mauris ipsum erat, consequat ut augue eget, ultricies interdum felis. Nunc a augue ac ex pretium ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed pellentesque erat.', 'Nulla auctor orci in fringilla posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed euismod eleifend lacus imperdiet laoreet. Integer a ultrices nisl. Nulla maximus nibh turpis, a sodales sapien cursus cursus.', 'Morbi porttitor ipsum ut ullamcorper gravida.', 'Activo');

INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(1, '2019-12-20', 'Sed luctus lobortis augue, non pharetra lectus lobortis vel. Mauris id vulputate arcu. Duis imperdiet orci vel tortor lacinia, a congue ipsum pellentesque. Nulla auctor orci in fringilla posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed euismod eleifend lacus imperdiet laoreet. Integer a ultrices nisl. Nulla maximus nibh turpis, a sodales sapien cursus cursus.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(2, '2020-01-10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel pretium odio, non fermentum augue. Fusce luctus et ligula ut consequat. Morbi magna purus, aliquet vestibulum auctor at, aliquet nec risus. Proin quis viverra ex. Maecenas lacus neque, euismod nec volutpat at, condimentum vitae lacus. Curabitur vehicula mi sed sem pulvinar aliquet sed sed ipsum. Fusce scelerisque egestas porttitor.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(3, '2020-01-22', 'Donec egestas pretium ante, eu dapibus libero tristique at. Mauris in diam nisi. Nunc quis sapien condimentum, interdum tellus vitae, molestie nisl. Fusce faucibus augue viverra mi iaculis tincidunt. Phasellus non ornare dui, et accumsan metus. Curabitur vel tristique sapien, quis pretium nisl. Cras tristique sit amet neque consectetur tempor. Donec lacus ipsum, dapibus ut turpis vel, porta iaculis sem. Vestibulum pharetra, quam sit amet vehicula gravida, nulla sem rutrum orci, eu tincidunt lectus tortor faucibus erat. Donec malesuada lacinia ante, vitae pharetra tortor eleifend in. Praesent eu arcu et tortor placerat pellentesque.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(4, '2020-02-15', 'Donec ac eleifend tortor, molestie imperdiet elit. Aenean vel arcu non diam gravida condimentum. Vestibulum nec quam sapien. Integer tincidunt convallis elit a pretium. Morbi porttitor ipsum ut ullamcorper gravida.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(5, '2020-02-26', 'Nulla auctor orci in fringilla posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed euismod eleifend lacus imperdiet laoreet. Integer a ultrices nisl. Nulla maximus nibh turpis, a sodales sapien cursus cursus.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(6, '2020-03-09', 'Nullam non vestibulum tellus. Proin semper pellentesque rhoncus. Vestibulum auctor mi turpis, sed sodales leo dictum a. Proin bibendum nunc tincidunt, auctor magna sed, lacinia neque. Mauris faucibus, libero at rutrum rhoncus, ipsum nunc rhoncus nunc, eget sagittis ex augue sed magna. Donec ac eleifend tortor, molestie imperdiet elit. Aenean vel arcu non diam gravida condimentum. Vestibulum nec quam sapien. ', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(1, '2020-03-17', 'Proin volutpat at sem vel hendrerit. Aliquam porttitor velit sit amet erat tincidunt, id tincidunt lorem lacinia. Suspendisse sit amet sem et ipsum cursus tempor. Nunc quis nulla nisi. Suspendisse nunc mauris, fermentum nec turpis eu, scelerisque imperdiet eros. Mauris ipsum erat, consequat ut augue eget, ultricies interdum felis. Nunc a augue ac ex pretium ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed pellentesque erat.', 'Activo', 1);
INSERT INTO sesion_terapia(nro_sesion, fecha_sesion, observaciones, estado, id_ficha) VALUES(2, '2020-04-01', 'Integer nec purus dapibus, laoreet neque ut, fermentum urna. Pellentesque eu gravida lacus. Ut laoreet nisi nunc. Mauris pharetra malesuada ex, ut sollicitudin felis bibendum a. Cras elementum lorem quis feugiat commodo. Phasellus non ligula et velit aliquet pharetra eget in enim. Nulla eget consequat arcu.', 'Activo', 1);

UPDATE paciente SET id_ficha = 1 WHERE id_paciente = 1;
UPDATE paciente SET id_ficha = 2 WHERE id_paciente = 2;

INSERT INTO usuario(nombre, apellido, username, password, enabled) VALUES('Patricio', 'Lara Hadi', '', '', 1);
INSERT INTO usuario(nombre, apellido, username, password, enabled) VALUES('Carmen', 'Brandt', '', '', 1);

INSERT INTO rol(nombre) VALUES('ROLE_PSICOLOGO_TRATANTE');
INSERT INTO rol(nombre) VALUES('ROLE_COLABORADOR');

INSERT INTO usuario_rol(user_id, rol_id) VALUES(1, 1);
INSERT INTO usuario_rol(user_id, rol_id) VALUES(1, 2);
INSERT INTO usuario_rol(user_id, rol_id) VALUES(2, 2);